-- populate_niches.sql
-- Phase 8: Catálogo de Nichos — 150+ nichos iniciais distribuídos por 10 categorias
-- Run once on VPS: psql -U extrator -d extrator -f populate_niches.sql
-- Idempotent: ON CONFLICT (name) DO NOTHING

INSERT INTO niches (name, category, priority, keywords) VALUES
-- Saúde (18 niches, priority 10)
('Clínica Médica',           'Saúde', 10, ARRAY['clinica medica', 'consultorio medico', 'medico especialista']),
('Clínica Odontológica',     'Saúde', 10, ARRAY['clinica odontologica', 'dentista', 'consultorio dentario']),
('Clínica Veterinária',      'Saúde', 10, ARRAY['clinica veterinaria', 'veterinario', 'pet veterinario']),
('Clínica de Estética',      'Saúde', 10, ARRAY['clinica estetica', 'estetica medica', 'procedimento estetico']),
('Clínica de Fisioterapia',  'Saúde', 10, ARRAY['fisioterapia', 'clinica fisio', 'reabilitacao fisioterapia']),
('Clínica de Psicologia',    'Saúde', 10, ARRAY['psicologia', 'psicologo', 'consultorio psicologia']),
('Farmácia',                 'Saúde', 10, ARRAY['farmacia', 'drogaria', 'farmacia popular']),
('Hospital Particular',      'Saúde', 10, ARRAY['hospital particular', 'hospital privado', 'pronto socorro particular']),
('Laboratório de Análises',  'Saúde', 10, ARRAY['laboratorio analises', 'exames laboratoriais', 'laboratorio clinico']),
('Clínica de Nutrição',      'Saúde', 10, ARRAY['nutricao', 'nutricionista', 'clinica nutricao']),
('Clínica de Dermatologia',  'Saúde', 10, ARRAY['dermatologia', 'dermato', 'clinica de pele']),
('Clínica de Ortopedia',     'Saúde', 10, ARRAY['ortopedia', 'ortopedista', 'clinica ortopedica']),
('Clínica de Cardiologia',   'Saúde', 10, ARRAY['cardiologia', 'cardiologista', 'clinica cardiologica']),
('Clínica de Pediatria',     'Saúde', 10, ARRAY['pediatria', 'pediatra', 'clinica pediatrica']),
('Clínica de Oftalmologia',  'Saúde', 10, ARRAY['oftalmologia', 'oftalmo', 'clinica ocular']),
('Clínica de Ginecologia',   'Saúde', 10, ARRAY['ginecologia', 'ginecologo', 'clinica ginecologica']),
('Clínica de Urologia',      'Saúde', 10, ARRAY['urologia', 'urologista', 'clinica urologica']),
('Centro Médico',            'Saúde', 10, ARRAY['centro medico', 'policlinica', 'multispecialidades']),

-- Beleza & Estética (15 niches, priority 20)
('Salão de Beleza',                         'Beleza & Estética', 20, ARRAY['salao beleza', 'cabeleireiro', 'studio hair']),
('Barbearia',                               'Beleza & Estética', 20, ARRAY['barbearia', 'barbeiro', 'barber shop']),
('Estúdio de Tatuagem',                     'Beleza & Estética', 20, ARRAY['tatuagem', 'tattoo studio', 'estudio tattoo']),
('Clínica de Depilação',                    'Beleza & Estética', 20, ARRAY['depilacao', 'laser depilacao', 'clinica depilacao']),
('Estúdio de Manicure',                     'Beleza & Estética', 20, ARRAY['manicure', 'pedicure', 'studio manicure']),
('Spa',                                     'Beleza & Estética', 20, ARRAY['spa', 'spa relaxamento', 'day spa']),
('Centro de Estética',                      'Beleza & Estética', 20, ARRAY['estetica', 'centro estetico', 'esteticista']),
('Loja de Cosméticos',                      'Beleza & Estética', 20, ARRAY['cosmeticos', 'loja beleza', 'produtos estetica']),
('Clínica de Micropigmentação',             'Beleza & Estética', 20, ARRAY['micropigmentacao', 'micropigmentista', 'design sobrancelhas']),
('Studio de Pilates',                       'Beleza & Estética', 20, ARRAY['pilates', 'studio pilates', 'pilates reformer']),
('Estúdio de Yoga',                         'Beleza & Estética', 20, ARRAY['yoga', 'estudio yoga', 'meditacao yoga']),
('Centro de Massagem',                      'Beleza & Estética', 20, ARRAY['massagem', 'massoterapia', 'clinica massagem']),
('Clínica de Podologia',                    'Beleza & Estética', 20, ARRAY['podologia', 'podologista', 'cuidados pes']),
('Estúdio de Alongamento de Cílios',        'Beleza & Estética', 20, ARRAY['cilios', 'extensao cilios', 'lash studio']),
('Instituto de Beleza',                     'Beleza & Estética', 20, ARRAY['instituto beleza', 'escola estetica', 'centro beleza']),

-- Alimentação (18 niches, priority 15)
('Restaurante',         'Alimentação', 15, ARRAY['restaurante', 'casa de comida', 'almoco restaurante']),
('Pizzaria',            'Alimentação', 15, ARRAY['pizzaria', 'pizza delivery', 'pizza artesanal']),
('Hamburgueria',        'Alimentação', 15, ARRAY['hamburgueria', 'burger', 'hamburguer artesanal']),
('Padaria',             'Alimentação', 15, ARRAY['padaria', 'panificadora', 'bakery']),
('Sorveteria',          'Alimentação', 15, ARRAY['sorveteria', 'gelato', 'sorvete artesanal']),
('Cafeteria',           'Alimentação', 15, ARRAY['cafeteria', 'cafe', 'coffee shop']),
('Churrascaria',        'Alimentação', 15, ARRAY['churrascaria', 'churrasco', 'rodizio carne']),
('Lanchonete',          'Alimentação', 15, ARRAY['lanchonete', 'snack bar', 'lanches']),
('Sushi',               'Alimentação', 15, ARRAY['sushi', 'culinaria japonesa', 'temaki delivery']),
('Doceria',             'Alimentação', 15, ARRAY['doceria', 'brigadeiros', 'doces finos']),
('Confeitaria',         'Alimentação', 15, ARRAY['confeitaria', 'bolos decorados', 'confeiteiro']),
('Empório',             'Alimentação', 15, ARRAY['emporio', 'emporio gourmet', 'produtos naturais']),
('Bar e Petiscaria',    'Alimentação', 15, ARRAY['bar petiscaria', 'petiscos', 'happy hour']),
('Açougue',             'Alimentação', 15, ARRAY['acougue', 'carnes', 'açougue premium']),
('Marmitaria',          'Alimentação', 15, ARRAY['marmitaria', 'marmitas', 'quentinha delivery']),
('Bistrô',              'Alimentação', 15, ARRAY['bistro', 'bistrô gourmet', 'culinaria francesa']),
('Comida Árabe',        'Alimentação', 15, ARRAY['comida arabe', 'esfirra', 'esfiha delivery']),
('Comida Japonesa',     'Alimentação', 15, ARRAY['comida japonesa', 'yakisoba', 'culinaria asiatica']),

-- Serviços Profissionais (18 niches, priority 20)
('Escritório de Advocacia',         'Serviços Profissionais', 20, ARRAY['advocacia', 'advogado', 'escritorio juridico']),
('Escritório de Contabilidade',     'Serviços Profissionais', 20, ARRAY['contabilidade', 'contador', 'escritorio contabil']),
('Consultoria Empresarial',         'Serviços Profissionais', 20, ARRAY['consultoria empresarial', 'consultor negocios', 'gestao empresarial']),
('Agência de Marketing',            'Serviços Profissionais', 20, ARRAY['agencia marketing', 'marketing digital', 'consultoria marketing']),
('Agência de Publicidade',          'Serviços Profissionais', 20, ARRAY['agencia publicidade', 'publicidade propaganda', 'comunicacao visual']),
('Seguradora',                      'Serviços Profissionais', 20, ARRAY['seguradora', 'seguro vida', 'corretora seguros']),
('Corretora de Seguros',            'Serviços Profissionais', 20, ARRAY['corretora seguros', 'seguros gerais', 'plano saude corretor']),
('Despachante',                     'Serviços Profissionais', 20, ARRAY['despachante', 'despachante documentos', 'regularizacao veicular']),
('Cartório',                        'Serviços Profissionais', 20, ARRAY['cartorio', 'registro imoveis', 'cartorio notas']),
('Tradutora',                       'Serviços Profissionais', 20, ARRAY['traducao', 'tradutora juramentada', 'interprete']),
('Gráfica',                         'Serviços Profissionais', 20, ARRAY['grafica', 'impressao grafica', 'grafica digital']),
('Empresa de Segurança',            'Serviços Profissionais', 20, ARRAY['seguranca privada', 'vigilancia', 'empresa seguranca']),
('Agência de Recursos Humanos',     'Serviços Profissionais', 20, ARRAY['rh', 'recursos humanos', 'agencia emprego']),
('Escritório de Arquitetura',       'Serviços Profissionais', 20, ARRAY['arquitetura', 'arquiteto', 'escritorio arquitetura']),
('Escritório de Engenharia',        'Serviços Profissionais', 20, ARRAY['engenharia', 'engenheiro', 'escritorio engenharia']),
('Consultoria de TI',               'Serviços Profissionais', 20, ARRAY['consultoria ti', 'tecnologia informacao', 'suporte informatica']),
('Empresa de Logística',            'Serviços Profissionais', 20, ARRAY['logistica', 'transportadora', 'distribuicao logistica']),
('Empresa de Transporte',           'Serviços Profissionais', 20, ARRAY['transporte', 'frete', 'empresa transporte']),

-- Educação (15 niches, priority 20)
('Escola Particular',           'Educação', 20, ARRAY['escola particular', 'colegio privado', 'ensino fundamental']),
('Escola de Idiomas',           'Educação', 20, ARRAY['escola idiomas', 'ingles', 'curso idiomas']),
('Escola de Música',            'Educação', 20, ARRAY['escola musica', 'musico', 'aula musica']),
('Escola de Dança',             'Educação', 20, ARRAY['escola danca', 'danca', 'studio danca']),
('Escola de Artes',             'Educação', 20, ARRAY['escola artes', 'artes plasticas', 'atelie artesanato']),
('Faculdade Particular',        'Educação', 20, ARRAY['faculdade particular', 'ensino superior privado', 'universidade particular']),
('Curso Profissionalizante',    'Educação', 20, ARRAY['curso profissionalizante', 'cursos tecnicos', 'qualificacao profissional']),
('Pré-Escola',                  'Educação', 20, ARRAY['pre escola', 'educacao infantil', 'creche']),
('Jardim de Infância',          'Educação', 20, ARRAY['jardim infancia', 'jardim escola', 'bercario']),
('Escola de Futebol',           'Educação', 20, ARRAY['escola futebol', 'escolinha futebol', 'futbol kids']),
('Escola de Natação',           'Educação', 20, ARRAY['escola natacao', 'natacao infantil', 'aula natacao']),
('Escola de Artes Marciais',    'Educação', 20, ARRAY['artes marciais', 'judo', 'jiu jitsu academia']),
('Escola de Informática',       'Educação', 20, ARRAY['escola informatica', 'curso computacao', 'informatica criancas']),
('Cursinho Pré-Vestibular',     'Educação', 20, ARRAY['cursinho pre vestibular', 'pre vestibular', 'preparatorio enem']),
('Escola de Gastronomia',       'Educação', 20, ARRAY['escola gastronomia', 'curso culinaria', 'gastronomia curso']),

-- Automotivo (15 niches, priority 30)
('Oficina Mecânica',                'Automotivo', 30, ARRAY['oficina mecanica', 'mecanica geral', 'auto centro']),
('Auto Peças',                      'Automotivo', 30, ARRAY['auto pecas', 'pecas carro', 'autopecas']),
('Loja de Pneus',                   'Automotivo', 30, ARRAY['pneus', 'loja pneus', 'pneus e rodas']),
('Lavagem de Carros',               'Automotivo', 30, ARRAY['lavagem carros', 'lava jato', 'auto lavagem']),
('Auto Elétrica',                   'Automotivo', 30, ARRAY['auto eletrica', 'eletrica automotiva', 'injecao eletronica']),
('Funilaria e Pintura',             'Automotivo', 30, ARRAY['funilaria pintura', 'lanternagem', 'polimento automotivo']),
('Concessionária',                  'Automotivo', 30, ARRAY['concessionaria', 'revenda veiculos', 'dealer automotivo']),
('Despachante Veicular',            'Automotivo', 30, ARRAY['despachante veicular', 'transferencia veiculo', 'documentacao carro']),
('Som Automotivo',                  'Automotivo', 30, ARRAY['som automotivo', 'multimidia carro', 'instaladora som']),
('Blindagem Veicular',              'Automotivo', 30, ARRAY['blindagem veicular', 'carro blindado', 'blindagem automotiva']),
('Locadora de Carros',              'Automotivo', 30, ARRAY['locadora carros', 'aluguel carro', 'rent a car']),
('Posto de Gasolina',               'Automotivo', 30, ARRAY['posto gasolina', 'posto combustivel', 'gasolineira']),
('Borracharia',                     'Automotivo', 30, ARRAY['borracharia', 'conserto pneu', 'vulcanizacao']),
('Distribuidor de Autopeças',       'Automotivo', 30, ARRAY['distribuidor autopecas', 'distribuicao autopecas', 'atacado pecas auto']),
('Instaladora de Acessórios',       'Automotivo', 30, ARRAY['acessorios carro', 'instaladora acessorios', 'personalizacao veicular']),

-- Varejo & Comércio (18 niches, priority 25)
('Supermercado',                    'Varejo & Comércio', 25, ARRAY['supermercado', 'mercado', 'atacarejo']),
('Farmácia Drogaria',               'Varejo & Comércio', 25, ARRAY['farmacia drogaria', 'drogaria', 'medicamentos']),
('Pet Shop',                        'Varejo & Comércio', 25, ARRAY['pet shop', 'petshop', 'loja animais']),
('Loja de Roupas',                  'Varejo & Comércio', 25, ARRAY['loja roupas', 'confeccoes', 'moda feminina']),
('Loja de Calçados',                'Varejo & Comércio', 25, ARRAY['loja calcados', 'sapataria', 'calcados esportivos']),
('Loja de Móveis',                  'Varejo & Comércio', 25, ARRAY['loja moveis', 'moveis planejados', 'movelaria']),
('Loja de Eletrodomésticos',        'Varejo & Comércio', 25, ARRAY['eletrodomesticos', 'loja eletrodomestico', 'linha branca']),
('Loja de Informática',             'Varejo & Comércio', 25, ARRAY['loja informatica', 'computadores', 'notebooks']),
('Loja de Brinquedos',              'Varejo & Comércio', 25, ARRAY['loja brinquedos', 'brinquedos infantis', 'toy store']),
('Loja de Artigos Esportivos',      'Varejo & Comércio', 25, ARRAY['artigos esportivos', 'equipamentos esporte', 'loja esporte']),
('Ótica',                           'Varejo & Comércio', 25, ARRAY['otica', 'oculos', 'loja otica']),
('Joalheria',                       'Varejo & Comércio', 25, ARRAY['joalheria', 'joias', 'ourives']),
('Floricultura',                    'Varejo & Comércio', 25, ARRAY['floricultura', 'flores', 'buque flores']),
('Livraria',                        'Varejo & Comércio', 25, ARRAY['livraria', 'livros', 'papelaria livraria']),
('Papelaria',                       'Varejo & Comércio', 25, ARRAY['papelaria', 'material escritorio', 'material escolar']),
('Loja de Presentes',               'Varejo & Comércio', 25, ARRAY['loja presentes', 'artigos presente', 'gift shop']),
('Mercadinho',                      'Varejo & Comércio', 25, ARRAY['mercadinho', 'minimercado', 'mercearia']),
('Bazar',                           'Varejo & Comércio', 25, ARRAY['bazar', 'variedades', 'loja popular']),

-- Construção & Imóveis (15 niches, priority 30)
('Imobiliária',                         'Construção & Imóveis', 30, ARRAY['imobiliaria', 'corretor imoveis', 'aluguel imovel']),
('Construtora',                         'Construção & Imóveis', 30, ARRAY['construtora', 'construcao civil', 'obra construtora']),
('Empreiteira',                         'Construção & Imóveis', 30, ARRAY['empreiteira', 'empreiteiro', 'construcao empreitada']),
('Loja de Materiais de Construção',     'Construção & Imóveis', 30, ARRAY['materiais construcao', 'loja construcao', 'home center']),
('Empresa de Reforma',                  'Construção & Imóveis', 30, ARRAY['reforma', 'empresa reforma', 'reforma residencial']),
('Empresa de Pintura Residencial',      'Construção & Imóveis', 30, ARRAY['pintura residencial', 'pintor', 'pintura predial']),
('Empresa de Limpeza',                  'Construção & Imóveis', 30, ARRAY['limpeza', 'limpeza residencial', 'empresa limpeza']),
('Empresa de Dedetização',              'Construção & Imóveis', 30, ARRAY['dedetizacao', 'controle pragas', 'dedetizadora']),
('Empresa de Mudança',                  'Construção & Imóveis', 30, ARRAY['mudanca', 'frete mudanca', 'empresa mudanca']),
('Marmoraria',                          'Construção & Imóveis', 30, ARRAY['marmoraria', 'marmore granito', 'pedras naturais']),
('Serralheria',                         'Construção & Imóveis', 30, ARRAY['serralheria', 'serralheiro', 'metalurgica']),
('Vidraçaria',                          'Construção & Imóveis', 30, ARRAY['vidracaria', 'vidro temperado', 'esquadrias vidro']),
('Empresa de Energia Solar',            'Construção & Imóveis', 30, ARRAY['energia solar', 'painel solar', 'instalacao solar']),
('Engenharia Civil',                    'Construção & Imóveis', 30, ARRAY['engenharia civil', 'engenheiro civil', 'projeto estrutural']),
('Empresa de Instalação Elétrica',      'Construção & Imóveis', 30, ARRAY['instalacao eletrica', 'eletricista', 'eletrica predial']),

-- Tecnologia (12 niches, priority 40)
('Empresa de Software',                 'Tecnologia', 40, ARRAY['software', 'desenvolvimento software', 'empresa ti']),
('Agência de Desenvolvimento Web',      'Tecnologia', 40, ARRAY['desenvolvimento web', 'agencia web', 'criacao sites']),
('Empresa de Suporte de TI',            'Tecnologia', 40, ARRAY['suporte ti', 'manutencao computadores', 'helpdesk']),
('Loja de Informática',                 'Tecnologia', 40, ARRAY['loja informatica', 'equipamentos ti', 'assistencia tecnica']),
('Empresa de Cloud Computing',          'Tecnologia', 40, ARRAY['cloud computing', 'nuvem ti', 'servicos cloud']),
('Startup de Tecnologia',               'Tecnologia', 40, ARRAY['startup', 'startup tecnologia', 'inovacao ti']),
('Empresa de Cibersegurança',           'Tecnologia', 40, ARRAY['ciberseguranca', 'seguranca digital', 'cyber security']),
('Empresa de Automação Industrial',     'Tecnologia', 40, ARRAY['automacao industrial', 'automacao', 'sistemas automacao']),
('Empresa de E-commerce',               'Tecnologia', 40, ARRAY['e-commerce', 'loja online', 'plataforma ecommerce']),
('Empresa de Impressão 3D',             'Tecnologia', 40, ARRAY['impressao 3d', '3d printing', 'prototipagem rapida']),
('Empresa de Inteligência Artificial',  'Tecnologia', 40, ARRAY['inteligencia artificial', 'ia', 'machine learning']),
('Empresa de App Mobile',               'Tecnologia', 40, ARRAY['app mobile', 'aplicativo', 'desenvolvimento app']),

-- Turismo & Lazer (12 niches, priority 35)
('Hotel',               'Turismo & Lazer', 35, ARRAY['hotel', 'hospedagem', 'hotel executivo']),
('Pousada',             'Turismo & Lazer', 35, ARRAY['pousada', 'hospedagem pousada', 'inn']),
('Hostel',              'Turismo & Lazer', 35, ARRAY['hostel', 'albergue', 'alojamento economico']),
('Agência de Viagens',  'Turismo & Lazer', 35, ARRAY['agencia viagens', 'turismo', 'pacotes viagem']),
('Parque de Diversões', 'Turismo & Lazer', 35, ARRAY['parque diversoes', 'parque atracao', 'entretenimento familia']),
('Boliche',             'Turismo & Lazer', 35, ARRAY['boliche', 'bowling', 'lazer boliche']),
('Clube Esportivo',     'Turismo & Lazer', 35, ARRAY['clube esportivo', 'clube recreativo', 'associacao esportiva']),
('Academia de Ginástica','Turismo & Lazer', 35, ARRAY['academia ginastica', 'gym', 'musculacao academia']),
('Estúdio de Crossfit', 'Turismo & Lazer', 35, ARRAY['crossfit', 'box crossfit', 'treinamento funcional']),
('Espaço para Eventos', 'Turismo & Lazer', 35, ARRAY['espaco eventos', 'buffet eventos', 'salon eventos']),
('Buffet',              'Turismo & Lazer', 35, ARRAY['buffet', 'buffet infantil', 'casa de festas buffet']),
('Casa de Festas',      'Turismo & Lazer', 35, ARRAY['casa festas', 'salao festas', 'espaco festivo'])
ON CONFLICT (name) DO NOTHING;
